#!/usr/bin/env bash
# Debugging nginx installation

#Requirement: Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
#Bug: sudo nginx status returns 'not running'; netstat -lpn does not show port 80
#Solution: https://stackoverflow.com/questions/16021481/nginx-not-listening-to-port-80

sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
