#!/usr/bin/env bash
# Using what I did for task #0, but made it short and sweet.
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
kill -9 "$(cat /run/nginx.pid)"
