#!/usr/bin/env bash
# This script displays numbers from 1 to 100 with "FizzBuzz", "Fizz", and
# "Buzz" instead of numbers that are multiple of 3 and 5 together, multiple
# of 3, and multiple of 5 respectively
i=1
while [ $i -le 100 ]
do
    ((fizz = i % 3))
    ((buzz = i % 5))
    if [ $fizz -eq 0 ] && [ $buzz -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $fizz -eq 0 ]
    then
	echo "Fizz"
    elif [ $buzz -eq 0 ]
    then
	echo "Buzz"
    else
	echo "$i"
    fi

    i=$(( i+1))
done
