#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd in a made up story

while IFS=: read -r username passwd userid groupid useridinfo home cmshell;
do
	echo "The user $username is part of the $groupid Gang, lives in $home and rides $cmshell. $userid's place is protected by the passcode $passwd, more info about the user here: $useridinfo"
done < /etc/passwd
