#!/usr/bin/env bash
# This script displays "Best School" for 10 times but "Hi" for the 9th iteration
i=0
while [ $i -le 9 ]
do
	if [ $i -eq 8 ]
	then
		echo "Hi"
		i=$(( i+1))
	else
		echo "Best School"
		i=$(( i+1))
	fi
done