#!/usr/bin/env bash
# This script displays "Best School" for 10 times but for the 4th iteration
# display "bad luck" and "good luck" for the 8th iteration
i=0
while [ $i -le 9 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	   	i=$(( i+1 ))
	elif [ $i -eq 7 ]
	then
		echo "good luck"
		i=$(( i+1))
	else
		echo "Best School"
		i=$(( i+1 ))
	fi
done