#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
h=0
while [ $h -le 12 ]
do
	echo "Hour: $h"
	h=$(( h+1))
	m=1
	while [ $m -le 59 ]
	do
		echo $m
		m=$(( m+1))
	done
done