#!/usr/bin/env bash
# This script gives user information about the school file
if [ -e school ]
then
    echo "school file exists"
else
    echo "school file does not exist"
fi

if [ -f school ]
then
    if [ -s school ]
    then
	echo "school file is not empty"
    else
	echo "school file is empty"
    echo "school is a regular file"
    fi
elif [ -d school ]
then
    echo "school file is not empty"
fi
