#!/usr/bin/env bash
# This script configures an Ubuntu server with the below requirements

cp /etc/hosts hosts_new
sed -i s/127.*$/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g hosts_new
cp -f hosts_new /etc/hosts
